// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP39GY5huYAYEQ8lyngoPa06azU1Xymc0',
    appId: '1:781652002810:web:b02b8df813bacea01d4643',
    messagingSenderId: '781652002810',
    projectId: 'diario-firebase-4f0b8',
    authDomain: 'diario-firebase-4f0b8.firebaseapp.com',
    storageBucket: 'diario-firebase-4f0b8.firebasestorage.app',
    measurementId: 'G-E9SQ4J0L4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4s4d0ns8NTJtx9a6LdnLR9BXvSj2CMuw',
    appId: '1:781652002810:android:aab47cc13354a4f81d4643',
    messagingSenderId: '781652002810',
    projectId: 'diario-firebase-4f0b8',
    storageBucket: 'diario-firebase-4f0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIGe2g8hUys84fxHWuoJNcf9qGxJZegvI',
    appId: '1:781652002810:ios:23ebb433cf5b72731d4643',
    messagingSenderId: '781652002810',
    projectId: 'diario-firebase-4f0b8',
    storageBucket: 'diario-firebase-4f0b8.firebasestorage.app',
    iosBundleId: 'com.example.diarioFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIGe2g8hUys84fxHWuoJNcf9qGxJZegvI',
    appId: '1:781652002810:ios:23ebb433cf5b72731d4643',
    messagingSenderId: '781652002810',
    projectId: 'diario-firebase-4f0b8',
    storageBucket: 'diario-firebase-4f0b8.firebasestorage.app',
    iosBundleId: 'com.example.diarioFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP39GY5huYAYEQ8lyngoPa06azU1Xymc0',
    appId: '1:781652002810:web:dc8f61a5cd3a26691d4643',
    messagingSenderId: '781652002810',
    projectId: 'diario-firebase-4f0b8',
    authDomain: 'diario-firebase-4f0b8.firebaseapp.com',
    storageBucket: 'diario-firebase-4f0b8.firebasestorage.app',
    measurementId: 'G-QP8EDVSPWZ',
  );
}
